"""empty message

Revision ID: afbf83aaa40d
Revises: 468d93dc2d97
Create Date: 2020-03-18 03:56:07.733193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afbf83aaa40d'
down_revision = '468d93dc2d97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'hashed_psw')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hashed_psw', sa.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
